config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #"get '/articles'" é mapeada para(to) a ação 'index' de 'ArticlesController':
  #get "/articles", to: "articles#index"
  
  #Essa 'route'abaixo é outra rota 'get', mas tem algo extra sem seu 'path', o ':id'.Isso designa um parâmetro de rota.Um parâmetro de rota captura um segmento do caminho da solicitação e coloca esse valor no 'Params' Hash, que é acessível pela ação do controlador.Por exemplo, ao lidar com uma solicitação como 'Get http://localhost:3000/articles/1', '1' seria capturado como o valor para ':id', que seria acessível como 'params[:id]' na action show de ArticlesContoller:
  #get"/articles/:id", to: "articles#show"

  #O Rails fornece um método de rotas chamado 'resources', que mapeia todas as rotas convencionais para uma coleção de recursos, como artigos. Portanto, antes de prosseguirmos para as seções 'C', 'U' e 'D', vamos substituir as duas rotas 'get' em 'config/routes.rb' por 'resources':
  
  #Isso abaixo cria 'comments' como um recurso aninhado nos artigos. Está é outra parte da captura da relação herárquica que existe entre 'articles' e 'comments':

  #Após fazer essa alteração abaixo, poderemos criar o 'controler' correspondente através do comando 'rails generate controler Comments' no shell de comando.
  root "articles#index"
  resources :articles do
    resources :comments
  end
end

app/models/article.rb
class Article < ApplicationRecord
    #Como vimos, a criação de um 'resource' é um processo de várias etapas. A manipulação de entrada inválida do usuário é outra etapa desse processo.O 'Rails' fornece um recurso chamado "validations' para nos ajudar a lidar com entradas de usuários inválidas. As 'validations' são regras que são verificadas antes que um objeto de 'model' seja salvo. Se qualquer uma das verificações falhar, o salvamento será interrompido e as mensagens de erro apropriadas serão adicionadas ao atributo errors do objeto modelo."
    #Vamos adicionar algumas validações ao nosso 'model' em 'app/models/article.rb'
    validates :title, presence: true #Essa primeira validação declara que um valor de 'title' deve estar presente. Como o título é uma string, isso significa que o valor do 'title' deve conter pelo menos um caractere qu não seja um espaço em branco.
    validates :body, presence: true, length: { minimum: 10 } #Essa segunda validação declara que um valor de 'body' também deve estar presente. Além disso, ele declara que o valor do 'body' deve ter pelo menos 10 caracteres.
    #Obs: Você pode estar se perguntando onde os atributos de título e corpo são definidos. O 'Active Record' define automaticamente os atributos do modelo para cada coluna da tabela, portanto, você não precisa declarar esses atributos em seu arquivo de 'model'.
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
  def index
    @articles = Article.all
  end

  #Por padrão, a Action 'show' renderizará 'app/views/articles/show.html.erb':
  def show
    #'params[:id]' tem que ter sido mencionado em 'routes.rb', em: get"/articles/:id", to: "articles#show"
    #A Action 'show' chama 'Article.find' com o 'id' capturado pelo parâmetro de rota. O 'article' retonado é armazenado na variável de instância '@article', portanto, é acessível pela visualização. Por padrão, a action 'show renderizará 'app/views/articles/show.html.erb'.
    @article = Article.find(params[:id])

    #Esse condicional abaixo foi recomendado pelo 'chatGPT', pois estava dando erro 'ActiveRecord: :RecordNotFound (Couldn't find Article with 'id'=2):
    if @article.nil?
      flahs[:error] = "Article not found"
      redirect_to articles_path
    else
      @articles = Article.where.not(id: @article.id)
    end
  end
  
  #Agora passamos para o 'C'(Create) do CRUD. Normalmente, em aplicativos da Web, a criação de um novo recurso é um processo de várias etapas. Primeiro, o usuário solicita um formulário para preencher. Em seguida, o usuário envia o formulário. Se não houver erros, o recurso será criado e algum tipo de confirmação será exibida. Caso contrário, o formulário é reexibido com mensagen de erro e o processo é repetido.
  #Em um aplicativ oRails, essas etapas são tratadas convencionalmente pelas ações 'new' e 'create' de um controlador. Vamos adicionar uma implementação típica dessas ações em 'app/controllers/articles_controller.rb, abaixo da ação 'show':
  #Quando visitamos 'http://3000/articles/new, a solicitação 'get /articles/new é mapeada para a nova 'action'. A nova 'action' não tenta salvar '@article'. Portanto, as validações não são verificadas e não haverá ensagens de erro.
  #Quando enviamos o formulário, a solicitação 'POST /articles' é mapeada para a 'action' 'create'. A ação de criação tenta salvar '@article'. Portanto, as 'validations' são verificadas. Se alguma validação falhar, '@article' não será salvo e 'app/views/articles/new.html.erb' será renderizado com mensgens de erro.
  def new #Por padrão essa action 'new' vai renderizar:'app/views/articles/new.html.erb'
    @article = Article.new
  end

  def create
    #@article = Article.new(title: "...", body: "...")
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article #Se o 'article' foi salvo com sucesso essa 'action' redirecionará para "http://localhost:3000/articles/#{@article.id}"
    else
      render :new, status: :unprocessable_entity #Se o 'article' não foi salvo, a 'action' reexibe o formulário renderizando 'app/views/articles/new.html.erb' com o código de status '422 unprocessable Entity'. O título e o corpo aqui são valores fictícios.
    end
  end
  
  #O "update" de um 'resource' é muito semehante à criação de um recurso. Ambos são processos de várias etapas. Primeiro, o usuário solicita um formulário para editar os dados. Em seguida, o usuário envia o formulário. Se não houver erros, o 'resource' será atualizado. Caso contrário, o formulário é reexibido com mensagens de erro e o processo é repetido.
  #Essas etapas são tratadas convencionalmente pelas 'actions' de 'edit' e 'update' de um controlador. Vamos adicionar uma implementação típica dessas 'actions' a 'app/controllers/articles_controller.rb'
  #Note que as 'actions' 'edit' e 'update' se assemelham às 'actions' 'new' e 'create'.
  #A 'action' de 'edit' busca o 'article' do banco de dados e o armazena em '@article' para que possa ser usado ao criar o formulário. Por padrão, a 'action' de 'edit' renderizará 'app/views/articles/edit.html.erb'.
  #A 'action' de 'update' (re)busca o artigo do banco de dados e tenta atualizá-lo com os dados do formulário enviado filtrado por 'article_params'. Se nenhuma 'validation' falha e o 'update' for bem-sucedido, a 'action redireciona o navegador para a página do 'article'. Caso contrário, a 'action' reexibe o formulário com mensagens de erro, renderizando assim 'app/views/articles/edit.html.erb'.

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  #Exluir um recurso é um processo mais simples do que criá-lo(create) ou atualizá-lo(update). Requer apenas uma rota(route) e uma 'action' do controlador. E nosso roteamento engenhoso ('resourceful routing', através de 'resources :articles) já fornece a rota, que mapeia as solicitações 'DELETE /articles/:id' para a action 'destroy' de ArticlesController.
  #Então, vamos adicionar uma action de 'destroy' típica a 'app/controllers/articles_controller.rb', abaixo da action de 'update':

  def destroy
    @article = Article.find(params[:id]) #A 'action' 'destroy' busca um 'article' no banco de dados e chama o 'destroy' nele.
    @article.destroy #Em seguida, ele redireciona o navegador para o caminho raiz com o código de status 303 See Other.
    redirect_to root_path, status: :see_other #Optamos por redirecionar para o caminho raiz porque esse é o nosso principal ponto de acesso para 'articles'. Mas, em outras circunstâncias, você pode optar por redirecionar para, por exemplo, 'articles_path'.
  end


  #---------------------------------------------------------------------------------------------------
  #Os dados de 'formulário' enviados são colocados no hash de parâmetros, juntamente com os parâmetros de rota capturados. Assim, a ação 'create' pode acessar o 'title' enviado por meio de 'params[:article][:title]' e o 'body' enviado por meio de 'params[:article][:body]'. Poderíamos passar esses valores individualmente para 'Articles.new, mas isso seria detalhado e possivelmente sujeito a erros. E ficaria pior à medida que adicionássemos mais campos.
  #Passaremos um único Hash que contém os valores. No entanto, ainda devemos especificar quais valores são permitidos nesse Hash. Caso contrário, um usuário mal intencionado poderia enviar campos de formulário extras e sobrescrever dados privados. De fato, se passarmos o Hash 'params[:article]' não filtrado diretamente pára 'Article.new, o Rails gerará um ForbiddenAttributesError para nos alertar sobre o problema. Portanto, usaremos um recurso do Rails chamado 'Strong Parameters' para filtrar os parâmetros. Pense nisso como digitação forte para parâmetros:
    private
      def article_params
        params.require(:article).permit(:title, :body)
      end
end

#Obs: 'redirect_to' fará com que o navegador faça uma nova solicitação, enquanto 'render' renderiza a exibição especificada para a solicitação atual. É importante usar o 'redirect_to' depois de alterar o estado do banco de dados ou do aplicativo. Caso contrário, se o usuário atualizar a página, o navegador fará a mesma solicitação e a mutação será repetida.

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<!--Nosso formulário do 'edit' terá a mesma aparência do nosso formulário 'new'. Até o código será o mesmo, graças ao construtor de formulários Rails(form Builder) e ao roteamento engenhoso(resourceful routing). O 'form builder' configura automaticamente o formulário para fazer o tipo apropriado de solicitação, com base no fato de o objeto model ter sido salvo anteriormente.
Como o código será o mesmo, vamos fatorá-lo em uma visão compartilhada chamada 'parcial'. Vamos criar app/views/articles/_form.html.erb' com o seguinte conteúdo: -->
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<!-- O código acima é igual ao nosso formulário em 'app/views/articles/new.html.erb', exceto que todas as ocorrências de '@article' foram substituídas por 'article'. Como os 'partials' são códigos compartilhados, a melhor prática é que eles não dependam de variáveis de instância específicas definidas por uma 'action' do controlador. Em vez disso, passaremos o 'artical' para a 'partial' como uma variável local.-->

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>
<!--Foi feito acima a mesma coisa que o arquivo 'app/views/articles/new.html.erb', pois ambos, ou seja, o 'new.html.erb' e o 'edit.html.erb' compartilharão da mesma 'partial' chamada '_form.html.erb', não repetindo assim códigos, já que se eu não fosse fazer sem a 'partial' sendo compartilhada, digitaria o mesmo código para as duas! Deixando meu código mais verboso.  -->

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>
<h1>Hello, Rails!</h1>
<hr>
<br>
<ul>
    <%#Se eu colocar '<%= @articles.each do |article|', imprimir'um por um. %>
    <% @articles.each do |article| %>
        <li>
            <!-- <a href="/articles/<%= article.id %>"> -->
            <!--<a href="<%= article_path(article) %>"> -->
                <%= link_to article.title, article %> <!--Mostra em formato de link: 'Hello Rails', que me vai levar para o link "/articles/<%= article.id %>"-->
        </li>
    <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<!--<h1>New Article</h1>

<%= form_with model: @article do |form| %>
    <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        Com nossas 'validations' em vigor, vamos modificar 'app/views/articles/new.html.erb' para exibir qualquer mensagem de erro para 'title' e 'body': -->
        <!--O método 'full_messages_for' retorna um 'Hash' de mensagens de erro amigáveis para um atributo especificado. Se não houver erros para esse atributo, a matriz estará vazia.
        <% @article.errors.full_messages_for(:title).each do |message| %>
            <div><%= message %></div>
        <% end %>    
    </div>

    <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
        <% @article.errors.full_messages_for(:body).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit %> #É aqui que se é adicionado o botão "Create Article"
    </div>
<% end %>

O nome de arquivo de um 'partial' deve ser prefixado com um underline, por exemplo: '_form.html.erb'.Mas ao rendenizar, é referenciado sem o underline, por exemplo: 'render "form"'.
Vamos atualizar 'app/views/articles/new.html.erb' para usar a 'partial' via renderização: -->
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
    <!--Linkando essa view 'show.html.erb' com a view 'app/views/articles/edit.html.erb':-->
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <!--Logo abaixo, usamos a opção 'data' para definir os atributos 'HTML data-turbo-method e data-turbo-confirm' do link 'Destroy'. Ambos os atributos se conectam ao Turbo, que é incluído por padrão em novos aplicativos Rails. O "data-turbo-method='delete'" fará com que o link faça uma solicitação DELETE em vez de uma solicitação 'get'. O "data-turbo-confirm='Tem certeza?" fará com que uma caixa de diálogo de confirmação apareça quando o link for clicado. Se o usuário cancelar a caixa de diálogo, a solicitação será abortada: -->
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %></li>
</ul>